### ISSUE TITLE
User unable to complete SVR activities on reaching the max lifetime. 

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#18]
25/5/22 freeosgov2 v0.9.16, current iteration 459269.
Login as freeosgov2. Set paramater table 'userlifespan' = 455766 (for testing purposes only).
User: vivvestin, registered_iteration = 3503 
Last iteration to run any SVR actions = 459269(registered_iteration + 455766).
Hence, user has exactly reached the max lifetime allowance and should be able to complete SVR activities.
Unable to run Survey, Vote or Ratify. 
Error: assertion failure with message: user has exceeded the maximum number of iterations
![freeosgov2 - XPR Account - Proton Testnet 24-05-2022 16-24-48](https://user-images.githubusercontent.com/77765830/169948633-49dba106-d502-4e1c-a54b-5512c7a8b2ab.png)

**Comment by tommccann777** [comment]
There is a misunderstanding. The last iteration is: registered_iteration + lifespan - 1, otherwise you are counting too many. Take a very simple example: user registers in iteration 1, lifespan is 2. The user should be able to vote in iteration 1 and 2, i.e. their 'life' lasts for 2 iterations. The last iteration they can vote on is 2 (1 + 2 -1)

**Comment by judytan21** [comment]
25/5/22 Retest in  freeosgov2 v0.9.17 current iter 459287, vivvestin
User has exactly reached the max lifespan as user's last iteration matches current iteration.
Last iteration 459287 = 3503 (registered_iteration) + 455785 (lifespan) - 1
Vote successful. Issue fixed. Close.
