### ISSUE TITLE
Survey completion recorded incorrectly in svrs table.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#3]
13/12/21 Contract: freeosgov, account: ellaevery, Version# v0.7.5, Bloks.io
When completing the first survey for ellaevery, the iteration# was recorded in the survey4 field. Expecting the iteration# to be stored in the survey1 field.
Steps:
1. Register ellaevery
2. Run Survey action for user ellaevery at 03:12:21 PM within the Survey start/end time.
3. Survey successful.
4. Check svrs table. Scope: ellaevery

![Account - !Proton Testnet 14-12-2021 11-01-38](https://user-images.githubusercontent.com/77765830/145895907-8b96fbe8-0052-46f1-ad6e-667d2f5efe20.png)

**Comment by tommccann777** [comment]
This is correct behaviour. I checked out the SVR record for survey and vote. I should explain how SVRs are recorded. First of all, the iteration number will be high (2139 in this case) because iterations are hourly and begin at the system.init time which is set to 2021-09-15T00:00:00.000 (UTC Timezone). Secondly, it uses a modulus technique to work out whether to write to field 'survey1', 'survey2'... 'survey4'. Here's the code for that:

switch (this_iteration % 4) {
            case 0: svr.survey1 = this_iteration; break;
            case 1: svr.survey2 = this_iteration; break;
            case 2: svr.survey3 = this_iteration; break;
            case 3: svr.survey4 = this_iteration; break;
}

What this means is it takes the iteration number (2139) performs modulus 4 arithmetic (divide by 4 and take the remainder). This gives 3. The code above says if the modulus is 3 then write the iteration number to 'survey4' field. That is what we are seeing.

The technique is an efficient way of cycling around the 4 fields.

**Comment by judytan21** [comment]
11/5/22 This is a very old issue. v0.9.10 Governance dApp is now using modulus 5 instead of Mod 4 technique for storing activities in SVRS table. Working fine.
